- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      apt: name=unzip
      apt: name=zip
      tags:
        - node
        - zsh
        - java
  tasks:
  - name: Install zsh
    apt: name=zsh
    tags:
    - zsh
  - name: Change Shell
    shell: zsh
    tags:
    - zsh
  - name: Install oh my zsh
    shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
    tags:
    - zsh
  - name: Install the zsh plugin autosuggestions
    ansible.builtin.git:
      repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
      dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
    tags:
    - zsh
  - name: Install node
    apt:
      name: ['nodejs', 'npm']
    tags:
    - node
  - name: Install n
    npm :
      name: n
      global: true
    tags:
    - node
  - name: Node 14
    shell: n 14
    tags:
    - node
  - name: Install sdkman
    shell: curl -s "https://get.sdkman.io" | bash 
    tags:
    - java
  - name: Init sdkman
    shell: source "$HOME/.sdkman/bin/sdkman-init.sh"
    tags:
    - java
  - name: Install default Java Temurin
    shell: sdk install java
    tags:
    - java

