- hosts: localhost
  become: true
  pre_tasks:
    - name: Update cache
      apt:
        update_cache: true
      apt: name=unzip
      apt: name=zip
      tags:
        - node
        - zsh
        - java
  tasks:
  - include: tasks/zsh.yml
    #- include: tasks/node.yml
  - name: Install sdkman
    shell: curl -s "https://get.sdkman.io" | bash 
    tags:
    - java
  - name: Init sdkman
    shell: source "$HOME/.sdkman/bin/sdkman-init.sh"
    tags:
    - java
  - name: Install default Java Temurin
    shell: sdk install java
    tags:
    - java

