- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Add Google Chrome repository (for Debian-based systems)
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Google Chrome (for Debian-based systems)
  apt:
    name: google-chrome-stable
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Google Chrome (for Red Hat-based systems)
  yum:
    name: https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-*.rpm
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

- name: Install Chrome Extensions
  become_user: lewis
  community.general.chrome_extension:
    name: "Void Theme - Black and Minimal"
    state: present
  tags:
  - chrome

- name: Install LastPass Extension
  become_user: lewis
  community.general.chrome_extension:
    name: "LastPass"
    state: present
  tags:
  - chrome

- name: Install JSON Formatter Extension
  become_user: lewis
  community.general.chrome_extension:
    name: "JSON Formatter"
    state: present
  tags:
  - chrome

- name: Install Vimium Extension
  become_user: lewis
  community.general.chrome_extension:
    name: "Vimium"
    state: present
  tags: 
  - chrome
