- name: Create 'lewis' User
  user:
    name: lewis
    password: "root"
    createhome: yes
    state: present
  tags: user

- name: Add 'lewis' to the sudo group
  user:
    name: lewis
    groups: sudo
    append: yes
  tags: user
