- name: Install SDKMAN!
  become_user: lewis
  shell: "curl -s https://get.sdkman.io | bash"
  args:
    creates: "/home/{{ your_username }}/.sdkman"
    tags:
    - java

- name: Source SDKMAN! setup script
  become_user: lewis
  shell: "source '/home/{{ your_username }}/.sdkman/bin/sdkman-init.sh'"
  tags:
  - java
  environment:
    SDKMAN_CANDIDATES_API: https://api.sdkman.io/2/candidates
    SDKMAN_PLATFORM: linux

- name: Install default Java version
  become_user: lewis
  shell: "sdk install java"
  tags:
  - java
