- name: Install SDKMAN!
  become: true
  shell: "curl -s https://get.sdkman.io | bash"
  args:
    creates: "/root/.sdkman"
    tags:
    - java

- name: Source SDKMAN! setup script
  become: true
  shell: "source '/root/.sdkman/bin/sdkman-init.sh'"
  tags:
  - java
  environment:
    SDKMAN_CANDIDATES_API: https://api.sdkman.io/2/candidates
    SDKMAN_PLATFORM: linux

- name: Install default Java version
  become: true
  shell: "sdk install java"
  tags:
  - java
